import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import baseUrl from '../helpers/baseUrl'
import { categoryList, contentType } from "../types";
import { useState } from 'react'

const Home: NextPage <{
  content: Array<categoryList>;
}> = ({content
})  => {
    const [contentCategory, setContentCategory] = useState(content);
console.log(content)
const [click ,setClick] = useState()
const [modalShow ,setModalShow] = useState(false)


let array = []

console.log(click)

  return (
    <div className='container-fluid '>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-danger'>
        {contentCategory.map((item) => (
          <div className='row'>
            <h2 className="pt-10 color-wh" key={item.id} >{item.title}</h2>
            {item.items.map((item) => (
          <button className="card col-md col col-sm" onClick={()=>{array.push(item);
          setModalShow(true)}}>
          <img className="card-img-top h-200rem w-20rem" src={item.photoUrL} width={100} height={200} alt="Card image cap"/>
          <div className="card-body">
            <p className="card-text">{item.title}</p>
          </div>
        </button>
        ))}
          </div>
        ))}
        </div>
        <button type="button" className="btn btn-primary">Submit</button>


        {modalShow && <div>
          <img className="card-img-top h-200rem w-20rem" src={click.photoUrL} width={100} height={200} alt="Card image cap"/>
          <div className="card-body">
            <p className="card-text">{click.title}</p>
          </div>
        </div> }

    </div>
  )
}

export async function getStaticProps(){
  const res =  await fetch(`${baseUrl}`)
  const data = await res.json()
  console.log("products ??",data.items)
  return {
    props:{
     // title:data?.title,
      content:data.items
    }
  }
 }

export default Home
