import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import baseUrl from "../helpers/baseUrl";
import { categoryList, contentType } from "../types";
import { useState } from "react";

const Home: NextPage<{
  content: Array<categoryList>;
}> = ({ content }) => {
  const [contentCategory, setContentCategory] = useState(content);
  console.log(content);
  const [click, setClick] = useState();
  const [modalShow, setModalShow] = useState(false);

  let array = [];

  console.log(click);

  return (
    <div className="bg-mycolor-backgroundColor">
      <Head>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap"
          rel="stylesheet"
        />
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="align-item-center"> */}
      <h1 className="text-3xl font-bold text-center  underline text-mycolor-fontcolor hover:text-mycolor-hoverfontcolor">
        Movie Awards 2021
      </h1>
      {/* </div> */}
      {contentCategory.map((item) => (
        <div className="bg-mycolor-backgroundColor ">
          <div>
            <h2 className="p-10  h-5  bg-slate-600 " key={item.id}>
              {item.title}
            </h2>
          </div>
          <div
            className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 lg:gap-3 md:gap-2 gap-1 justify-items-center mx-5 bg-mycolor-backgroundColor lg:min-h-25"
            onClick={() => {
              array.push(item);
              setModalShow(true);
            }}
          >
            {item.items.map((item) => (
              <div
                className=""
                onClick={() => {
                  array.push(item);
                  setModalShow(true);
                }}
              >
                <div className="py-10">
                  <div className="rounded overflow-hidden shadow-lg max-w-sm">
                    <img
                      className="w-full"
                      src={item.photoUrL}
                      alt="Card image cap"
                    />
                    <div className="font-bold text-md mb-10 px-6 py-4 bg-mycolor-fontcolor">
                      <p className="card-text text-center">{item.title}</p>
                    </div>
                    <div className="item-center justify-items-center bg-green-500 hover:bg-sky-700 hover:text-mycolor-hoverfontcolor">
                      <h1 className="text-3xl font-bold text-center ">
                        Select
                      </h1>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}

      <button type="button" className="btn btn-primary">
        Submit
      </button>

      {modalShow && (
        <div>
          <img
            className="card-img-top h-200rem w-20rem"
            src={click.photoUrL}
            width={100}
            height={100}
            alt="Card image cap"
          />
          <div className="card-body">
            <p className="card-text">{click.title}</p>
          </div>
        </div>
      )}
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch(`${baseUrl}`);
  const data = await res.json();
  console.log("products ??", data.items);
  return {
    props: {
      // title:data?.title,
      content: data.items,
    },
  };
}

export default Home;
